model_func: 
  - resnet18
  - alexnet
  - densenet121
  - vgg11
data_format:
  - Numpy arrays
  - Image files
# TODO: Find a way to test public dataset here, but would need some form of dry run,
#   otherwise it takes forever.
gpu:
  - False
  - True
checkpoint:
  - False
  - True
visualization_tool:
  - Not at all
  - Tensorboard
  - Aim
  - MLflow
  # TODO: Find a way to add comet.ml here, without requiring API key.
num_classes:
  - 10
  - 1000
pretrained: 
  - False
  - True
loss: CrossEntropyLoss
optimizer: Adam
lr: 0.001
batch_size: 128
num_epochs: 1
print_every: 1
