model_func: ResNet50
model_pre: resnet
data_format:
  - Numpy arrays
  - Image files
checkpoint:
  - True
  - False
visualization_tool:
  - Not at all
  - Tensorboard
pretrained: False
loss: "binary_crossentropy"
num_classes: 2
optimizer: Adam
lr: 0.001
batch_size: 128
num_epochs: 1